[package]
name = "politician-abuser"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
dotenvy = "0.15.7"
lettre = "0.10"
lettre_email = "0.9"
serde = { version = "1.0", features = ["derive"] }
